# k8s/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: fullstack-app
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: ZHl1d2FyYWphbGluZ2Ft
  MONGO_INITDB_ROOT_PASSWORD: bmV3cGFzc3dvcmQxMjM=

